import React, { useState, useEffect } from "react";
import api from "../../services/api";
import { useNavigate } from "react-router-dom";
import Stars from "../../components/Stars";
import BackButton from "../../components/BackButton";
import Toast from "../../components/Toast";
import { FaYoutube, FaSpinner, FaDownload, FaTrash, FaHistory, FaEdit, FaSave, FaBookmark, FaRegBookmark, FaFilePdf, FaFileWord } from "react-icons/fa";
import ReactMarkdown from "react-markdown";
import html2pdf from "html2pdf.js";

export default function VideoSummarizerPage() {
  const navigate = useNavigate();
  const [videoUrl, setVideoUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState(null);
  const [savedSummaries, setSavedSummaries] = useState([]);
  const [showHistory, setShowHistory] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [bookmarkStatus, setBookmarkStatus] = useState({});
  const [toast, setToast] = useState({ message: "", type: "success" });

  useEffect(() => {
    fetchSavedSummaries();
  }, []);

  const fetchSavedSummaries = async () => {
    try {
      const res = await api.get("/student/video/summaries");
      setSavedSummaries(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  const handleSummarize = async () => {
    if (!videoUrl.trim()) {
      setToast({ message: "Please enter a YouTube URL", type: "error" });
      return;
    }
    setLoading(true);
    try {
      const res = await api.post("/student/video/summarize", { videoUrl });
      setSummary(res.data.summary);
      setIsEditing(false);
      setToast({ message: res.data.isCached ? "Loaded from cache!" : "Summary generated!", type: "success" });
      fetchSavedSummaries();
      
      // Check if already bookmarked
      try {
        const bookmarksRes = await api.get("/student/bookmarks");
        const isBookmarked = bookmarksRes.data.some(b => b.itemId === res.data.summary._id && b.type === 'video');
        setBookmarkStatus({ [res.data.summary._id]: isBookmarked });
      } catch (err) {}
    } catch (err) {
      setToast({ message: err.response?.data?.message || "Failed to summarize", type: "error" });
    } finally {
      setLoading(false);
    }
  };

  const saveEdit = async () => {
    if (!summary) return;
    try {
      await api.put(`/student/video/summaries/${summary._id}`, { summary: editContent });
      setSummary({ ...summary, summary: editContent });
      setIsEditing(false);
      setToast({ message: "Summary updated!", type: "success" });
      fetchSavedSummaries();
    } catch (err) {
      setToast({ message: "Failed to save", type: "error" });
    }
  };

  const handleBookmark = async () => {
    if (!summary) return;
    try {
      if (bookmarkStatus[summary._id]) {
        // Find and delete bookmark
        const bookmarksRes = await api.get("/student/bookmarks");
        const bookmark = bookmarksRes.data.find(b => b.itemId === summary._id && b.type === 'video');
        if (bookmark) {
          await api.delete(`/student/bookmarks/${bookmark._id}`);
          setToast({ message: "Bookmark removed", type: "success" });
        }
      } else {
        await api.post("/student/bookmarks", {
          type: "video",
          itemId: summary._id,
          collectionName: "Videos",
          title: summary.title,
          subtitle: summary.author
        });
        setToast({ message: "Bookmarked successfully!", type: "success" });
      }
      setBookmarkStatus({ ...bookmarkStatus, [summary._id]: !bookmarkStatus[summary._id] });
    } catch (err) {
      setToast({ message: "Failed to bookmark", type: "error" });
    }
  };

  const deleteSummary = async (id) => {
    if (!window.confirm("Delete this summary permanently?")) return;
    try {
      await api.delete(`/student/video/summaries/${id}`);
      fetchSavedSummaries();
      if (summary?._id === id) setSummary(null);
      setToast({ message: "Deleted successfully", type: "success" });
    } catch (err) {
      setToast({ message: "Failed to delete", type: "error" });
    }
  };

  const loadSummary = (s) => {
    setSummary(s);
    setShowHistory(false);
    setIsEditing(false);
  };

  const downloadAsPDF = () => {
    const element = document.createElement('div');
    element.style.padding = '40px';
    element.style.fontFamily = 'Arial, sans-serif';
    element.innerHTML = `
      <h1 style="color: #4f46e5;">${summary.title}</h1>
      <h3 style="color: #6366f1;">By ${summary.author}</h3>
      <hr/>
      <div>${summary.summary.replace(/\n/g, '<br/>')}</div>
      <hr/>
      <p style="text-align: center; color: #999; font-size: 12px;">Generated by StudyPulse AI • ${new Date().toLocaleDateString()}</p>
    `;
    document.body.appendChild(element);
    html2pdf().set({ margin: 0.5, filename: `${summary.title}.pdf`, html2canvas: { scale: 2 }, jsPDF: { unit: 'in', format: 'a4' } }).from(element).save();
    document.body.removeChild(element);
    setToast({ message: "PDF downloaded!", type: "success" });
  };

  const downloadAsDOCX = () => {
    const content = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="UTF-8"><title>${summary.title}</title></head>
      <body>
        <h1>${summary.title}</h1>
        <h3>By ${summary.author}</h3>
        <hr/>
        <div>${summary.summary.replace(/\n/g, '<br/>')}</div>
        <hr/>
        <p>Generated by StudyPulse AI • ${new Date().toLocaleDateString()}</p>
      </body>
      </html>
    `;
    const blob = new Blob([content], { type: 'application/msword' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${summary.title}.doc`;
    link.click();
    URL.revokeObjectURL(link.href);
    setToast({ message: "Word document downloaded!", type: "success" });
  };

  return (
    <div className="video-page min-vh-100 py-5 position-relative">
      <Stars />
      <Toast message={toast.message} type={toast.type} onClose={() => setToast({ message: "", type: "success" })} />

      <div className="container">
        <BackButton to="/dashboard" label="← Back to Dashboard" />

        <div className="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3">
          <h2 className="text-white fw-bold">🎥 YouTube Video Summarizer</h2>
          <button onClick={() => { setShowHistory(!showHistory); fetchSavedSummaries(); }} className="btn-history">
            <FaHistory /> {showHistory ? "Hide History" : `History (${savedSummaries.length})`}
          </button>
        </div>

        {/* Input Section */}
        <div className="card input-card p-4 mb-4">
          <div className="row g-3">
            <div className="col-md-9">
              <input type="text" className="form-control form-input" placeholder="Paste YouTube URL here..." value={videoUrl} onChange={(e) => setVideoUrl(e.target.value)} />
            </div>
            <div className="col-md-3">
              <button className="btn-summarize w-100" onClick={handleSummarize} disabled={loading}>
                {loading ? <><FaSpinner className="spinner" /> Processing...</> : <><FaYoutube /> Summarize</>}
              </button>
            </div>
          </div>
        </div>

        {/* History Section */}
        {showHistory && (
          <div className="history-card mb-4 p-4">
            <h5>📚 Your Saved Summaries</h5>
            <div className="history-list">
              {savedSummaries.length === 0 ? (
                <p className="text-muted">No saved summaries yet</p>
              ) : (
                savedSummaries.map((s) => (
                  <div key={s._id} className="history-item" onClick={() => loadSummary(s)}>
                    <div className="history-info">
                      <div className="history-title">{s.title}</div>
                      <div className="history-meta">{s.author} • {new Date(s.savedAt).toLocaleDateString()}</div>
                    </div>
                    <button onClick={(e) => { e.stopPropagation(); deleteSummary(s._id); }} className="delete-history"><FaTrash /></button>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        {/* Summary Result */}
        {summary && (
          <div className="summary-card p-4">
            <div className="summary-header">
              <div>
                <h3>{summary.title}</h3>
                <p className="text-muted">By {summary.author}</p>
              </div>
              <div className="summary-actions">
                <button onClick={() => { setIsEditing(!isEditing); if (!isEditing) setEditContent(summary.summary); }} className="btn-edit" title="Edit">
                  <FaEdit /> Edit
                </button>
                {isEditing && (
                  <button onClick={saveEdit} className="btn-save" title="Save">
                    <FaSave /> Save
                  </button>
                )}
                <button onClick={downloadAsPDF} className="btn-pdf" title="Download PDF">
                  <FaFilePdf /> PDF
                </button>
                <button onClick={downloadAsDOCX} className="btn-word" title="Download Word">
                  <FaFileWord /> DOCX
                </button>
                <button onClick={handleBookmark} className="btn-bookmark" title="Bookmark">
                  {bookmarkStatus[summary._id] ? <FaBookmark style={{ color: '#facc15' }} /> : <FaRegBookmark />} Bookmark
                </button>
              </div>
            </div>
            <div className="summary-content">
              {isEditing ? (
                <textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} rows={20} className="edit-textarea" />
              ) : (
                <ReactMarkdown>{summary.summary}</ReactMarkdown>
              )}
            </div>
          </div>
        )}
      </div>

      <style>{`
        .video-page { background: linear-gradient(180deg, #080e18 0%, #122138 25%, #1e3652 50%, #28507e 75%, #1a2a3d 100%); }
        .btn-history { background: rgba(255,255,255,0.2); border: none; color: white; padding: 8px 20px; border-radius: 30px; cursor: pointer; }
        .input-card { background: linear-gradient(145deg, #ebf1f4ff, #bedaf3ff); border-radius: 20px; }
        .form-input { border-radius: 12px; padding: 12px; border: 1px solid #ddd; }
        .btn-summarize { background: linear-gradient(135deg, #ef4444, #dc2626); color: white; border: none; padding: 12px; border-radius: 12px; font-weight: 600; cursor: pointer; }
        .history-card { background: rgba(255,255,255,0.1); backdrop-filter: blur(10px); border-radius: 20px; color: white; }
        .history-list { max-height: 300px; overflow-y: auto; }
        .history-item { display: flex; justify-content: space-between; align-items: center; padding: 12px; background: rgba(255,255,255,0.1); border-radius: 12px; margin-bottom: 8px; cursor: pointer; }
        .history-item:hover { background: rgba(255,255,255,0.2); }
        .delete-history { background: none; border: none; color: #ef4444; cursor: pointer; }
        .summary-card { background: white; border-radius: 20px; }
        .summary-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; flex-wrap: wrap; gap: 10px; }
        .summary-actions { display: flex; gap: 8px; flex-wrap: wrap; }
        .btn-edit, .btn-save, .btn-pdf, .btn-word, .btn-bookmark { background: none; border: none; padding: 6px 12px; border-radius: 8px; cursor: pointer; display: inline-flex; align-items: center; gap: 5px; font-size: 12px; }
        .btn-edit { background: #f59e0b; color: white; }
        .btn-save { background: #22c55e; color: white; }
        .btn-pdf { background: #ef4444; color: white; }
        .btn-word { background: #3b82f6; color: white; }
        .btn-bookmark { background: #8b5cf6; color: white; }
        .summary-content { line-height: 1.6; max-height: 500px; overflow-y: auto; padding: 10px; }
        .edit-textarea { width: 100%; padding: 12px; border: 1px solid #ddd; border-radius: 12px; font-family: monospace; }
        .spinner { animation: spin 1s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @media (max-width: 768px) { .summary-header { flex-direction: column; } .summary-actions { width: 100%; justify-content: center; } }
      `}</style>
    </div>
  );
}