import React, { useState, useEffect } from "react";
import api from "../../services/api";
import { useNavigate } from "react-router-dom";
import Toast from "../../components/Toast";
import {
  FaYoutube,
  FaSpinner,
  FaDownload,
  FaTrash,
  FaHistory,
  FaEdit,
  FaSave,
  FaBookmark,
  FaRegBookmark,
  FaFilePdf,
  FaFileWord,
  FaEye,
} from "react-icons/fa";
import ReactMarkdown from "react-markdown";
import html2pdf from "html2pdf.js";

export default function VideoSummarizerPage() {
  const navigate = useNavigate();
  const [videoUrl, setVideoUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState(null);
  const [savedSummaries, setSavedSummaries] = useState([]);
  const [showHistory, setShowHistory] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [bookmarkStatus, setBookmarkStatus] = useState({});
  const [toast, setToast] = useState({ message: "", type: "success" });

  useEffect(() => {
    fetchSavedSummaries();
  }, []);

  const fetchSavedSummaries = async () => {
    try {
      const res = await api.get("/student/video/summaries");
      setSavedSummaries(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  const handleSummarize = async () => {
    if (!videoUrl.trim()) {
      setToast({ message: "Please enter a YouTube URL", type: "error" });
      return;
    }
    setLoading(true);
    try {
      const res = await api.post("/student/video/summarize", { videoUrl });
      setSummary(res.data.summary);
      setIsEditing(false);
      setToast({
        message: res.data.isCached
          ? "Loaded from cache!"
          : "Summary generated!",
        type: "success",
      });
      fetchSavedSummaries();

      try {
        const bookmarksRes = await api.get("/student/bookmarks");
        const isBookmarked = bookmarksRes.data.some(
          (b) => b.itemId === res.data.summary._id && b.type === "video",
        );
        setBookmarkStatus({ [res.data.summary._id]: isBookmarked });
      } catch (err) {}
    } catch (err) {
      setToast({
        message: err.response?.data?.message || "Failed to summarize",
        type: "error",
      });
    } finally {
      setLoading(false);
    }
  };

  const saveEdit = async () => {
    if (!summary) return;
    try {
      await api.put(`/student/video/summaries/${summary._id}`, {
        summary: editContent,
      });
      setSummary({ ...summary, summary: editContent });
      setIsEditing(false);
      setToast({ message: "Summary updated!", type: "success" });
      fetchSavedSummaries();
    } catch (err) {
      setToast({ message: "Failed to save", type: "error" });
    }
  };

  const handleBookmark = async () => {
    if (!summary) return;
    try {
      if (bookmarkStatus[summary._id]) {
        const bookmarksRes = await api.get("/student/bookmarks");
        const bookmark = bookmarksRes.data.find(
          (b) => b.itemId === summary._id && b.type === "video",
        );
        if (bookmark) {
          await api.delete(`/student/bookmarks/${bookmark._id}`);
          setToast({ message: "Bookmark removed", type: "success" });
        }
      } else {
        await api.post("/student/bookmarks", {
          type: "video",
          itemId: summary._id,
          collectionName: "Videos",
          title: summary.title,
          subtitle: summary.author,
        });
        setToast({ message: "Bookmarked successfully!", type: "success" });
      }
      setBookmarkStatus({
        ...bookmarkStatus,
        [summary._id]: !bookmarkStatus[summary._id],
      });
    } catch (err) {
      setToast({ message: "Failed to bookmark", type: "error" });
    }
  };

  const deleteSummary = async (id) => {
    if (!window.confirm("Delete this summary permanently?")) return;
    try {
      await api.delete(`/student/video/summaries/${id}`);
      fetchSavedSummaries();
      if (summary?._id === id) setSummary(null);
      setToast({ message: "Deleted successfully", type: "success" });
    } catch (err) {
      setToast({ message: "Failed to delete", type: "error" });
    }
  };

  const loadSummary = (s) => {
    setSummary(s);
    setShowHistory(false);
    setIsEditing(false);
  };

  const downloadAsPDF = () => {
    const element = document.createElement("div");
    element.style.padding = "40px";
    element.style.fontFamily = "Arial, sans-serif";
    element.innerHTML = `<h1 style="color: #4f46e5;">${summary.title}</h1><h3 style="color: #6366f1;">By ${summary.author}</h3><hr/><div>${summary.summary.replace(/\n/g, "<br/>")}</div><hr/><p style="text-align: center; color: #999; font-size: 12px;">Generated by StudyPulse AI • ${new Date().toLocaleDateString()}</p>`;
    document.body.appendChild(element);
    html2pdf()
      .set({
        margin: 0.5,
        filename: `${summary.title}.pdf`,
        html2canvas: { scale: 2 },
        jsPDF: { unit: "in", format: "a4" },
      })
      .from(element)
      .save();
    document.body.removeChild(element);
    setToast({ message: "PDF downloaded!", type: "success" });
  };

  const downloadAsDOCX = () => {
    const content = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${summary.title}</title></head><body><h1>${summary.title}</h1><h3>By ${summary.author}</h3><hr/><div>${summary.summary.replace(/\n/g, "<br/>")}</div><hr/><p>Generated by StudyPulse AI • ${new Date().toLocaleDateString()}</p></body></html>`;
    const blob = new Blob([content], { type: "application/msword" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${summary.title}.doc`;
    link.click();
    URL.revokeObjectURL(link.href);
    setToast({ message: "Word document downloaded!", type: "success" });
  };

  return (
    <div className="video-root">
      <div className="video-bg" />
      <div className="video-grid" />
      <div className="video-orb video-orb-a" />
      <div className="video-orb video-orb-b" />
      <Toast
        message={toast.message}
        type={toast.type}
        onClose={() => setToast({ message: "", type: "success" })}
      />

      <main className="video-main">
        <div className="video-container">
          <button className="video-back" onClick={() => navigate("/dashboard")}>
            Back to Dashboard
          </button>

          <div className="video-header">
            <div className="video-header-icon">
              <FaYoutube />
            </div>
            <div>
              <h1 className="video-title">
                YouTube <span className="video-grad">Summarizer</span>
              </h1>
              <p className="video-subtitle">
                Get AI-powered summaries of educational videos
              </p>
            </div>
            <button
              onClick={() => {
                setShowHistory(!showHistory);
                fetchSavedSummaries();
              }}
              className="history-btn"
            >
              <FaHistory />{" "}
              {showHistory
                ? "Hide History"
                : `History (${savedSummaries.length})`}
            </button>
          </div>

          <div className="input-card">
            <div className="input-group">
              <input
                type="text"
                className="video-input"
                placeholder="Paste YouTube URL here..."
                value={videoUrl}
                onChange={(e) => setVideoUrl(e.target.value)}
              />
              <button
                className="summarize-btn"
                onClick={handleSummarize}
                disabled={loading}
              >
                {loading ? (
                  <>
                    <FaSpinner className="spinner" /> Processing...
                  </>
                ) : (
                  <>
                    <FaYoutube /> Summarize
                  </>
                )}
              </button>
            </div>
          </div>

          {showHistory && (
            <div className="history-card">
              <h5>📚 Your Saved Summaries</h5>
              <div className="history-list">
                {savedSummaries.length === 0 ? (
                  <p className="text-muted">No saved summaries yet</p>
                ) : (
                  savedSummaries.map((s) => (
                    <div
                      key={s._id}
                      className="history-item"
                      onClick={() => loadSummary(s)}
                    >
                      <div className="history-info">
                        <div className="history-title">{s.title}</div>
                        <div className="history-meta">
                          {s.author} •{" "}
                          {new Date(s.savedAt).toLocaleDateString()}
                        </div>
                      </div>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          deleteSummary(s._id);
                        }}
                        className="delete-history"
                      >
                        <FaTrash />
                      </button>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {summary && (
            <div className="summary-card">
              <div className="summary-header">
                <div>
                  <h3>{summary.title}</h3>
                  <p className="text-muted">By {summary.author}</p>
                </div>
                <div className="summary-actions">
                  <button
                    onClick={() => {
                      setIsEditing(!isEditing);
                      if (!isEditing) setEditContent(summary.summary);
                    }}
                    className="edit-btn"
                  >
                    <FaEdit /> Edit
                  </button>
                  {isEditing && (
                    <button onClick={saveEdit} className="save-btn">
                      <FaSave /> Save
                    </button>
                  )}
                  <button onClick={downloadAsPDF} className="pdf-btn">
                    <FaFilePdf /> PDF
                  </button>
                  <button onClick={downloadAsDOCX} className="word-btn">
                    <FaFileWord /> DOCX
                  </button>
                  <button onClick={handleBookmark} className="bookmark-btn">
                    {bookmarkStatus[summary._id] ? (
                      <FaBookmark style={{ color: "#facc15" }} />
                    ) : (
                      <FaRegBookmark />
                    )}{" "}
                    Bookmark
                  </button>
                </div>
              </div>
              <div className="summary-content">
                {isEditing ? (
                  <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    rows={20}
                    className="edit-textarea"
                  />
                ) : (
                  <ReactMarkdown>{summary.summary}</ReactMarkdown>
                )}
              </div>
            </div>
          )}
        </div>
      </main>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@500;600;700;800&family=Inter:wght@300;400;500;600;700&display=swap');
        .video-root{--bg:#0a0c12;--surface:#111318;--border:rgba(88,130,255,0.12);--border-h:rgba(88,130,255,0.28);--accent:#5882ff;--accent2:#20e6d0;--violet:#9b7aff;--text:#edf2ff;--muted:#8e9cc4;--faint:#49587a;--fd:'Syne',sans-serif;--fb:'Inter',sans-serif;}
        *,*::before,*::after{margin:0;padding:0;box-sizing:border-box;}
        .video-root{font-family:var(--fb);background:var(--bg);color:var(--text);min-height:100vh;}
        .video-grad{background:linear-gradient(135deg,var(--accent),var(--accent2),var(--violet));-webkit-background-clip:text;-webkit-text-fill-color:transparent;}
        .video-bg{position:fixed;inset:0;z-index:0;background:radial-gradient(ellipse 60% 45% at 50% -5%,rgba(88,130,255,0.08) 0%,transparent 60%);}
        .video-grid{position:fixed;inset:0;z-index:0;background-image:linear-gradient(rgba(88,130,255,0.03)1px,transparent 1px),linear-gradient(90deg,rgba(88,130,255,0.03)1px,transparent 1px);background-size:48px 48px;}
        .video-orb{position:fixed;border-radius:50%;filter:blur(80px);pointer-events:none;z-index:0;}
        .video-orb-a{width:400px;height:400px;top:-100px;left:50%;transform:translateX(-50%);background:rgba(88,130,255,0.06);animation:orbFloat 12s infinite;}
        .video-orb-b{width:250px;height:250px;bottom:10%;right:-5%;background:rgba(32,230,208,0.04);animation:orbFloat2 10s infinite;}
        @keyframes orbFloat{0%,100%{transform:translateX(-50%) scale(1)}50%{transform:translateX(-50%) scale(1.1)}}
        @keyframes orbFloat2{0%,100%{transform:scale(1)}50%{transform:scale(1.15)}}
        .video-main{position:relative;z-index:10;max-width:1000px;margin:0 auto;padding:90px 2rem 3rem;min-height:100vh;}
        .video-back{display:inline-flex;align-items:center;gap:8px;background:rgba(88,130,255,0.1);border:1px solid var(--border);color:var(--accent);padding:8px 20px;border-radius:40px;font-size:0.85rem;cursor:pointer;margin-bottom:1.5rem;transition:all 0.2s;}
        .video-back:hover{background:rgba(88,130,255,0.2);transform:translateX(-4px);}
        .video-header{display:flex;align-items:center;gap:1rem;margin-bottom:2rem;flex-wrap:wrap;}
        .video-header-icon{width:60px;height:60px;background:rgba(88,130,255,0.1);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:1.8rem;color:var(--accent);}
        .video-title{font-family:var(--fd);font-size:1.8rem;font-weight:700;margin-bottom:0.25rem;}
        .video-subtitle{color:var(--muted);font-size:0.85rem;}
        .history-btn{background:rgba(255,255,255,0.05);border:1px solid var(--border);color:white;padding:8px 20px;border-radius:30px;cursor:pointer;display:flex;align-items:center;gap:8px;margin-left:auto;}
        .input-card{background:rgba(17,19,24,0.6);backdrop-filter:blur(12px);border:1px solid var(--border);border-radius:20px;padding:1.5rem;margin-bottom:1.5rem;}
        .input-group{display:flex;gap:1rem;flex-wrap:wrap;}
        .video-input{flex:3;padding:12px 16px;background:rgba(255,255,255,0.04);border:1px solid var(--border);border-radius:12px;color:var(--text);font-size:0.9rem;}
        .video-input:focus{outline:none;border-color:var(--accent);}
        .summarize-btn{padding:12px 24px;background:linear-gradient(135deg,#ef4444,#dc2626);border:none;border-radius:12px;color:white;font-weight:600;cursor:pointer;display:flex;align-items:center;gap:8px;}
        .history-card{background:rgba(17,19,24,0.6);backdrop-filter:blur(12px);border:1px solid var(--border);border-radius:20px;padding:1.5rem;margin-bottom:1.5rem;color:white;}
        .history-list{max-height:300px;overflow-y:auto;}
        .history-item{display:flex;justify-content:space-between;align-items:center;padding:12px;background:rgba(255,255,255,0.05);border-radius:12px;margin-bottom:8px;cursor:pointer;}
        .history-item:hover{background:rgba(255,255,255,0.1);}
        .history-title{font-weight:600;font-size:0.85rem;}
        .history-meta{font-size:0.7rem;opacity:0.6;margin-top:4px;}
        .delete-history{background:none;border:none;color:#ef4444;cursor:pointer;}
        .summary-card{background:white;border-radius:20px;overflow:hidden;}
        .summary-header{display:flex;justify-content:space-between;align-items:flex-start;padding:1.5rem;background:#f8f9fa;border-bottom:1px solid #e2e8f0;flex-wrap:wrap;gap:1rem;}
        .summary-header h3{color:#1e293b;}
        .summary-actions{display:flex;gap:8px;flex-wrap:wrap;}
        .edit-btn,.save-btn,.pdf-btn,.word-btn,.bookmark-btn{padding:6px 14px;border-radius:8px;cursor:pointer;font-size:0.75rem;display:flex;align-items:center;gap:6px;border:none;}
        .edit-btn{background:#f59e0b;color:white;}
        .save-btn{background:#22c55e;color:white;}
        .pdf-btn{background:#ef4444;color:white;}
        .word-btn{background:#3b82f6;color:white;}
        .bookmark-btn{background:#8b5cf6;color:white;}
        .summary-content{padding:1.5rem;line-height:1.6;max-height:500px;overflow-y:auto;}
        .edit-textarea{width:100%;padding:12px;border:1px solid #ddd;border-radius:12px;font-family:monospace;min-height:300px;}
        .spinner{animation:spin 0.8s linear infinite;}
        @keyframes spin{to{transform:rotate(360deg)}}
        @media(max-width:768px){
          .video-main{padding:80px 1rem 2rem;}
          .video-title{font-size:1.5rem;}
          .video-header{flex-direction:column;align-items:flex-start;}
          .history-btn{margin-left:0;width:100%;justify-content:center;}
          .input-group{flex-direction:column;}
          .summarize-btn{justify-content:center;}
          .summary-header{flex-direction:column;}
          .summary-actions{width:100%;justify-content:center;}
          .video-back{width:100%;justify-content:center;}
        }
      `}</style>
    </div>
  );
}
