import React from "react";
import { FaFilePdf, FaFileWord } from "react-icons/fa";
import html2pdf from "html2pdf.js";

export default function ExportNotes({ note, onExport }) {
  const exportAsPDF = async () => {
    const element = document.createElement('div');
    element.style.padding = '40px';
    element.style.fontFamily = 'Arial, sans-serif';
    element.style.maxWidth = '800px';
    element.style.margin = '0 auto';
    element.style.backgroundColor = 'white';
    element.style.color = 'black';
    element.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #4f46e5;">${note.subject}</h1>
        <h2 style="color: #6366f1;">${note.topic}</h2>
        <hr style="border-color: #e5e7eb;">
      </div>
      <div style="line-height: 1.6;">
        ${note.content.replace(/\n/g, '<br/>')}
      </div>
      <div style="text-align: center; margin-top: 50px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af;">
        Generated by StudyPulse AI • ${new Date().toLocaleDateString()}
      </div>
    `;
    
    document.body.appendChild(element);
    
    const opt = {
      margin: [0.5, 0.5, 0.5, 0.5],
      filename: `${note.subject}_${note.topic}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, letterRendering: true },
      jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
    };
    
    try {
      await html2pdf().set(opt).from(element).save();
      if (onExport) onExport('pdf');
    } catch (err) {
      console.error("PDF export error:", err);
      if (onExport) onExport('error');
    } finally {
      document.body.removeChild(element);
    }
  };
  
  const exportAsDOCX = () => {
    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${note.subject} - ${note.topic}</title>
        <style>
          body { font-family: 'Times New Roman', serif; margin: 1in; line-height: 1.5; }
          h1 { color: #4f46e5; }
          h2 { color: #6366f1; }
          .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #6c757d; }
        </style>
      </head>
      <body>
        <div style="text-align: center;">
          <h1>${note.subject}</h1>
          <h2>${note.topic}</h2>
          <hr>
        </div>
        <div>
          ${note.content.replace(/\n/g, '<br/>')}
        </div>
        <div class="footer">
          Generated by StudyPulse AI • ${new Date().toLocaleDateString()}
        </div>
      </body>
      </html>
    `;
    
    const blob = new Blob([content], { type: 'application/msword' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.href = url;
    link.download = `${note.subject}_${note.topic}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    if (onExport) onExport('docx');
  };
  
  return (
    <div className="export-buttons" style={{ display: 'inline-flex', gap: '8px' }}>
      <button 
        className="btn-export pdf" 
        onClick={exportAsPDF}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          padding: '6px 12px',
          borderRadius: '8px',
          border: 'none',
          cursor: 'pointer',
          fontWeight: '600',
          fontSize: '0.8rem',
          transition: 'all 0.3s',
          background: '#ef4444',
          color: 'white'
        }}
        onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
        onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
      >
        <FaFilePdf /> PDF
      </button>
      <button 
        className="btn-export word" 
        onClick={exportAsDOCX}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          padding: '6px 12px',
          borderRadius: '8px',
          border: 'none',
          cursor: 'pointer',
          fontWeight: '600',
          fontSize: '0.8rem',
          transition: 'all 0.3s',
          background: '#3b82f6',
          color: 'white'
        }}
        onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
        onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
      >
        <FaFileWord /> DOCX
      </button>
    </div>
  );
}