import React, { useEffect, useState } from "react";
import api from "../../../services/api";
import { Link, useNavigate } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import Stars from "../../../components/Stars";
import BackButton from "../../../components/BackButton";
import Toast from "../../../components/Toast";
import ExportNotes from "../../../components/ExportNotes";

export default function Notes() {
  const navigate = useNavigate();
  const [notes, setNotes] = useState([]);
  const [selected, setSelected] = useState(null);
  const [search, setSearch] = useState("");
  const [toast, setToast] = useState({ message: "", type: "success" });

  useEffect(() => {
    fetchNotes();
  }, []);

  const fetchNotes = async () => {
    try {
      const res = await api.get("/notes");
      setNotes(res.data);
    } catch (err) {
      setToast({ message: "Failed to load notes", type: "error" });
    }
  };

  const deleteNote = async (id) => {
    if (!window.confirm("Delete note?")) return;
    try {
      await api.delete(`/notes/${id}`);
      if (selected?._id === id) setSelected(null);
      setToast({ message: "Note deleted successfully!", type: "success" });
      fetchNotes();
    } catch (err) {
      setToast({ message: "Failed to delete note", type: "error" });
    }
  };

  const downloadPDF = async (note) => {
    const el = document.createElement("div");
    el.style.padding = "30px";
    el.style.background = "#fff";
    el.style.color = "#000";
    el.innerHTML = `
      <h2>${note.subject}</h2>
      <h4>${note.topic}</h4>
      <hr/>
      ${note.content.replace(/\n/g, "<br/>")}
      <div style="text-align: center; margin-top: 50px; font-size: 12px; color: #999;">
        Generated by StudyPulse AI • ${new Date().toLocaleDateString()}
      </div>
    `;
    document.body.appendChild(el);
    try {
      const canvas = await html2canvas(el, { scale: 2 });
      const img = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "pt", "a4");
      const w = pdf.internal.pageSize.getWidth();
      const h = (canvas.height * w) / canvas.width;
      pdf.addImage(img, "PNG", 0, 0, w, h);
      pdf.save(`${note.subject}_${note.topic}.pdf`);
      setToast({ message: "PDF downloaded successfully!", type: "success" });
    } catch (err) {
      setToast({ message: "Failed to generate PDF", type: "error" });
    } finally {
      document.body.removeChild(el);
    }
  };

  const handleExport = (type) => {
    setToast({ message: `Note exported as ${type.toUpperCase()}!`, type: "success" });
  };

  const filtered = notes.filter(
    (n) =>
      n.subject.toLowerCase().includes(search.toLowerCase()) ||
      n.topic.toLowerCase().includes(search.toLowerCase()),
  );

  return (
    <div className="notes-bg min-vh-100 py-5 position-relative">
      <Stars />
      <Toast message={toast.message} type={toast.type} onClose={() => setToast({ message: "", type: "success" })} />

      <div className="container">
        <BackButton to="/dashboard" label="← Back to Dashboard" />

        <div className="notes-header mb-4">
          <div>
            <h2 className="fw-bold text-light">📝 My Notes</h2>
            <p className="text-light-opacity">Manage your AI-generated notes</p>
          </div>
          <Link to="/notes/create" className="btn btn-gradient">
            ➕ Create Note
          </Link>
        </div>

        <div className="row g-4">
          {/* LEFT LIST */}
          <div className="col-md-4">
            <input
              className="form-control search-input mb-3"
              placeholder="🔍 Search notes..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <div className="notes-list">
              {filtered.map((note) => (
                <div
                  key={note._id}
                  className={`note-tile ${selected?._id === note._id ? "active" : ""}`}
                  onClick={() => setSelected(note)}
                >
                  <div>
                    <h6 className="mb-0">{note.subject}</h6>
                    <small className="note-topic">{note.topic}</small>
                  </div>
                  <button
                    className="btn btn-sm btn-outline-danger"
                    onClick={(e) => {
                      e.stopPropagation();
                      deleteNote(note._id);
                    }}
                  >
                    🗑
                  </button>
                </div>
              ))}
              {filtered.length === 0 && (
                <div className="text-center text-light-opacity py-4">
                  No notes found
                </div>
              )}
            </div>
          </div>

          {/* RIGHT VIEW */}
          <div className="col-md-8">
            {selected ? (
              <div className="card note-view shadow-lg border-0">
                <div className="note-view-header">
                  <div>
                    <h4>{selected.subject}</h4>
                    <span>{selected.topic}</span>
                  </div>
                  <button className="btn-close btn-close-white" onClick={() => setSelected(null)} />
                </div>
                <div className="note-actions">
                  <button
                    className="btn btn-sm btn-outline-primary"
                    onClick={() => navigate(`/notes/edit/${selected._id}`)}
                  >
                    ✏️ Edit
                  </button>
                  <button
                    className="btn btn-sm btn-outline-secondary"
                    onClick={() => downloadPDF(selected)}
                  >
                    📄 PDF
                  </button>
                  <ExportNotes note={selected} onExport={handleExport} />
                  <button
                    className="btn btn-sm btn-outline-danger"
                    onClick={() => deleteNote(selected._id)}
                  >
                    ❌ Delete
                  </button>
                </div>
                <div className="note-content">
                  <ReactMarkdown>{selected.content}</ReactMarkdown>
                </div>
              </div>
            ) : (
              <div className="empty-state">
                <h5>📖 Select a Note</h5>
                <p>Choose a note from the left to view its content</p>
              </div>
            )}
          </div>
        </div>
      </div>

      <style>{`
        .notes-bg {
          background: linear-gradient(180deg, #080e18 0%, #122138 25%, #1e3652 50%, #28507e 75%, #5a77a3 100%);
        }
        .text-light-opacity { color: rgba(255,255,255,0.8); }
        .notes-header { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 16px; }
        .search-input { 
          border-radius: 20px; 
          padding: 10px 14px;
          background: rgba(255,255,255,0.1);
          border: 1px solid rgba(255,255,255,0.2);
          color: white;
        }
        .search-input::placeholder { color: rgba(255,255,255,0.6); }
        .notes-list { max-height: 70vh; overflow-y: auto; }
        .note-tile {
          background: linear-gradient(145deg, #fdfdfd, #f5f5f5);
          padding: 14px;
          border-radius: 14px;
          margin-bottom: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
          cursor: pointer;
          transition: 0.3s;
        }
        .note-tile:hover { transform: translateY(-2px); }
        .note-tile.active { background: linear-gradient(135deg, #4f46e5, #6366f1); color: white; }
        .note-topic { color: rgba(0,0,0,0.6); }
        .note-tile.active .note-topic { color: rgba(255,255,255,0.8); }
        .note-view { border-radius: 18px; overflow: hidden; background: white; }
        .note-view-header {
          background: linear-gradient(135deg, #4f46e5, #6366f1);
          color: white;
          padding: 16px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .note-actions { padding: 12px; display: flex; gap: 10px; background: #f8f9fa; border-bottom: 1px solid #e5e7eb; flex-wrap: wrap; }
        .note-content { padding: 20px; line-height: 1.7; }
        .empty-state { height: 300px; display: flex; flex-direction: column; justify-content: center; align-items: center; background: white; border-radius: 18px; }
        .btn-gradient { background: linear-gradient(135deg, #4f46e5, #6366f1); border: none; color: white; }
        @media (max-width: 768px) {
          .notes-header { flex-direction: column; text-align: center; }
          .row.g-4 { flex-direction: column; }
          .notes-list { max-height: 300px; }
          .note-actions { justify-content: center; }
        }
      `}</style>
    </div>
  );
}